### ISSUE TITLE
Create a dev deployment based on a branch

### ISSUE THREAD

**Issue by jonny-wg2** [working-group-two/wgtwo.com#124]
Problem: One must always clone the repo and run the website locally to experience and see a change that is being worked on in a PR.
Goal: How can we automate a solution to deploy a dev website on netlify.com based on a pull request. 

Idea solution (could be a better solution but what comes to my mind)
1. Developer create a branch with their proposed changes 
2. We create a github action that will be triggered on say a `label` being added to a pr. The github action would rebase the PR on a separate branch, e.g. dev-pages
3. We configure netlify.com to deploy a site from the branch dev-pages
4. We can all go to "wgtwo-dev.netlify.com" to see the changes from the PR

Note: I haven't done much googling on best way to solve this problem but used netlify in the past.
Additional background: The current deployment is using github pages with github actions to build and deploy the site.

**Comment by torotimes** [comment]
@Prid13 You should take a look at this one. It might be a good development project for you. The first step now is to discuss various solutions - before we start developing something. 

In short, the idea is to set up a dev website so that we can collaborate without cloning and running repos locally.

**Comment by Prid13** [comment]
This sounds like a great idea. I honestly think the proposed solution is as good as it can get 😇⭐

Do I keep developing in my own fork, or should we start creating branches in the original repo? In any case, I'm going to need access to the original repo if I am to take on this task 😅

**Comment by torotimes** [comment]
@jonny-wg2 we need your input on this one! is there an internal consensus on how to execute this?

**Comment by jonny-wg2** [comment]
I have added you to now a Maintain role for this repo. If you need more access let me know. For example, you will need access to the GH actions.
<img width="876" alt="image" src="https://user-images.githubusercontent.com/39831372/188723607-0d46fb09-285c-4461-9e86-2c9e309ff0d0.png">


In short, I believe we could just create PRs from the branch and not use the fork/pr model.

You could also try to setup this on your own forked repo with GH actions and then once working, migrate it to this repo (but not needed). I could help setup the netlify for the real deployment.

Let me know if you have any other questions.

**Comment by Prid13** [comment]
@jonny-wg2 Finally made progress on this. Had to learn how to mentally parse Github Action YAML files 😅

Tried the rebase approach at first, but learned that Netlify could just "dump" all the files in a repo as-is onto its deployment server, so it made more sense to _build_ the website in the Github Action and deploy the build folder to `dev-pages` branch, which can now be deployed to Netlify as-is :)

Check out my proposed Action file: https://github.com/working-group-two/wgtwo.com/pull/132

The only thing left is to set up Netlify to deploy files from the `dev-pages` branch. Can you do that? I don't have the proper logins to Netlify, nor the permissions.

**Comment by jonny-wg2** [comment]
Great work. Will make the netlify plugin integration. Will hopefully have it done tomorrow evening.

**Comment by jonny-wg2** [comment]
@Prid13 so I got the website deployed now - was super simple with netlify. We have the domain https://wgtwo-dev.netlify.app/

I didn't think about it until just now, but we want to make sure that google and other search engines don't index the website.  From a super quick google I found these two articles - unsure if it's the best way to do it - but would you be able to take a look at preventing robots from indexing the new site?
- https://www.tempertemper.net/blog/stop-search-indexing-for-netlify-deploy-previews-and-branch-deploys

**Comment by jonny-wg2** [comment]
pr to update the readme https://github.com/working-group-two/wgtwo.com/pull/137

**Comment by jonny-wg2** [comment]
@Prid13 still an issue with the pipeline https://github.com/working-group-two/wgtwo.com/actions/runs/3083590830/jobs/4984705347#step:3:24

**Comment by jonny-wg2** [comment]
I merged your last pr and it appears to be working! Great job @Prid13
