### ISSUE TITLE
New blog post - Q&A with Stephane

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#126]
Hey @Prid13 

Can you set this up as a new blog post on /blog, please? 

I'd like to have an image above the truncate if possible. See our latest blog posts for reference. 

Here's the content:
https://docs.google.com/document/d/1q2ycPjP1mrnUoDlbawF7KtPOn_zDk96DgHGZhUwUrog/edit

![pic_0](https://user-images.githubusercontent.com/98818609/189202838-55053cba-20d6-40de-a4f8-c9eaffb61cc4.jpg)
![pic_1](https://user-images.githubusercontent.com/98818609/189202842-097d68cd-4ab2-4e19-a53d-919fa11d8ee0.jpg)
![Stephane](https://user-images.githubusercontent.com/98818609/189202848-778f0067-c42c-4fe8-a2fa-e53d15801859.jpg)

Is it possible to have descriptions under each image? I'd like to say that the first two images are "General illustration, courtesy Ericsson"

Under the picture of Stephane you could say "Stephane Savonitto"

Thanks so much!

**Comment by torotimes** [comment]
Hey again @Prid13 

I started making the post here - but we're not done. Can you have a look at my code? 

https://github.com/working-group-two/wgtwo.com/pull/127

**Comment by Prid13** [comment]
@torotimes GREAT job 👍!

Made a new component/element that lets you add images with a caption below them.
Check the latest commit and see if you're content with the results :)

**Comment by torotimes** [comment]
Thanks for collab on this, Zain!
