### ISSUE TITLE
Sharing buttons for blog posts

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#165]
Hey @Prid13  - right now we don't offer sharing buttons at the end (or top?) of our blog posts. 

We could experiment with setting up sharing for LinkedIn, Twitter and maybe Reddit? 

Do you wanna explore some options - or do you want me to suggest a couple of variations before you get started? 

I'd like to keep it clean and classy, not too dominant in terms of style and shape. 

There's some good thinking and a relatively nice implementation here:
https://medium.com/steven-krohn/stop-your-social-share-buttons-from-tracking-your-visitors-and-slowing-your-page-speeds-b5c5ed4e0056

@jonny-wg2 - any preferences from your end?

**Comment by jonny-wg2** [comment]
Posthog has a nice share button layout. I like how it's not in color - taking away from the content.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/39831372/196628074-4f33a3e2-cf31-487f-b585-a9a9563d4a87.png">

https://posthog.com/handbook/engineering/development-process

**Comment by jonny-wg2** [comment]
Perhaps we can do twitter, linkedin, reddit, email as share buttons

**Comment by Prid13** [comment]
Apologies for my tardiness, but here're some suggestions:

# At TOP

> ![Screenshot_8559](https://user-images.githubusercontent.com/27897747/196852646-2debf9d3-dd5c-43c3-b82e-bc0fb508355e.png)

> ![Screenshot_8562](https://user-images.githubusercontent.com/27897747/196852654-7900baca-e27b-4356-b43b-068df92fb16e.png)

# On SIDEBAR

![Screenshot_8560](https://user-images.githubusercontent.com/27897747/196852682-e0835035-6462-4d49-9331-3435fd58734c.png)

# At BOTTOM

![Screenshot_8561](https://user-images.githubusercontent.com/27897747/196852702-dd319ed4-f52e-47e3-b532-1ba1bcb69382.png)

-----

Personal preference: top _and_ bottom would be handy :)

**Comment by torotimes** [comment]
Hey @Prid13 

Good stuff!

Let's go for this option:

On top (not in sidebar): The four social buttons plus the link button. 

On bottom: the sharing tray, with a "drop down" with four buttons and the link button. 

See example implementation here

![image](https://user-images.githubusercontent.com/98818609/196928673-f469e870-6349-469c-8258-ede8d4602700.png)


![image](https://user-images.githubusercontent.com/98818609/196928610-358d4540-6957-454c-8bd7-ee12fd360158.png)

See full implementation here: 
https://blog.novelai.net/novelai-improvements-on-stable-diffusion-e10d38db82ac

**Comment by Prid13** [comment]
https://github.com/working-group-two/wgtwo.com/pull/173

**Comment by torotimes** [comment]
Really really nice first impression, Zain :) 

We're asking for input from the broader team. We'll get back to you with any feedback
