### ISSUE TITLE
About Pull Requests

### ISSUE THREAD

**Issue by apo2205** [working-group-two/wgtwo.com#167]
@torotimes
Am I correct in my understanding that pull requests are done after forking?

**Comment by torotimes** [comment]
Hi @apo2205 - yes you create a branch first. Then you do a pull request. 

@jonny-wg2  - just to introduce you into the conversation, Rikuya is with our Japanese dev/design partner. Feel free to chip in.

**Comment by jonny-wg2** [comment]
You can create pull requests directly from the repo - or - from your forked repository. Essentially you can follow any git workflow. 
Clone the repo
```
git clone https://github.com/working-group-two/wgtwo.com.git
```
Create your new branch
```
git checkout -b your-branch-name
```
Do you development and then add the updated files to your branch
```
git add .
```
Crate your commit message
```
git add -m "your commit message"
```
Push your changes 
```
git push --set-upstream origin your-branch-name
````

**Comment by jonny-wg2** [comment]
I have now updated the README.md with this content https://github.com/working-group-two/wgtwo.com/blob/main/README.md?plain=1#L10-L42

**Comment by apo2205** [comment]
Thanks for the detailed explanation. I threw in a pull request.

**Comment by torotimes** [comment]
Great - we're reviewing today!

@jonny-wg2, @Prid13 - wanna have a look at the code?
