### ISSUE TITLE
Fix footer color for all docs pages

### ISSUE THREAD

**Issue by jonny-wg2** [working-group-two/wgtwo.com#169]
Example of the issue on the footer https://www.wgtwo.com/docs/about/introduction/
<img width="1569" alt="image" src="https://user-images.githubusercontent.com/39831372/196930264-7fff858b-7d02-407e-8d51-3ed60268cb5f.png">

This issue only exists on wgtwo.com/docs/**** pages.

The solution should have the background color span a width 100% across the entire page.

**Comment by torotimes** [comment]
@Prid13 wanna take a look at this?

**Comment by torotimes** [comment]
@Prid13 has this one been resolved?

**Comment by Prid13** [comment]
Fixed with https://github.com/working-group-two/wgtwo.com/pull/202

Sorry, didn't see this issue until Tor's last bump, hence why it took so long 😅
