### ISSUE TITLE
Footer menu: Change from "Docs" to "About"

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#17]

**Comment by torotimes** [comment]
I didn't get that change. 

My take is that people expect a menu option saying "About" - to learn about our company. Case studies are secondary to that, imho.

**Comment by jonny-wg2** [comment]
ok updated https://github.com/working-group-two/wgtwo.com/commit/70a54052450e548fdad4c3dff838f46310611dc8
