### ISSUE TITLE
Have github actions auto apply yarn prettier in a new commit instead of failing the PR

### ISSUE THREAD

**Issue by jonny-wg2** [working-group-two/wgtwo.com#172]
Problem: People forget to run `yarn prettier` and people use the web GUI to make changes. We have a GH actions that checks if yarn prettier and will fail the PR if yarn prettier needs to run.

Goal: If a PR requires yarn prettier, have the pipeline run yarn prettier and update the PR in a new commit with the changes.

**Comment by torotimes** [comment]
Hey @Prid13 can you have a look at this one? It would be really helpful. :)

**Comment by Prid13** [comment]
Will fix this asap :)

**Comment by torotimes** [comment]
How's this one going, @Prid13 ?

**Comment by Prid13** [comment]
> How's this one going, @Prid13 ?

Sorry, was planning on finishing this over the weekend, but a lot of other stuff kept piling on :/ Will finish this by today 👍😇

**Comment by torotimes** [comment]
Very cool! 😊

**Comment by Prid13** [comment]
There we go: https://github.com/working-group-two/wgtwo.com/pull/189 🎉

**Comment by torotimes** [comment]
Takk!!!
