### ISSUE TITLE
Fixes on career page 

### ISSUE THREAD

**Issue by OdaAndersen** [working-group-two/wgtwo.com#178]
1. Change email address from Victoiria@wgtwo.com to Hicks@wgtwo.com. 
![image](https://user-images.githubusercontent.com/112557175/199474814-c5d6b0e2-8237-43d6-9200-2c4bfab651d1.png)

2. Update the following sentence "60+ engineers, 19+ different nationalities make up the wgtwo team. We collectively have spent centuries at Telenor, Telia, Ice, Google, PWC, Ericsson, Cisco, and more." to "75+ engineers, 25+ different nationalities make up the wgtwo team. We collectively have spent centuries at Telenor, Telia, Ice, Google, PWC, Ericsson, Cisco, and more"

**Comment by Prid13** [comment]
Finally fixed this -- sorry for the time it took, was a bit busy with other stuff 😅

The changes are available here: https://github.com/working-group-two/wgtwo.com/pull/180

Whenever someone is able to review them and approve them, you'll see them live on the official website :)
