### ISSUE TITLE
Blog: Add CTA component as standard at the end of every blog post

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#19]
Today we point readers to read the next or previous post when they are done reading a post. We should keep that. 

We should also have a standard CTA (call to action) - perhaps just the regular contact form component.

**Comment by torotimes** [comment]
28 April comment: Let's add the newsletter subscription form to the bottom of each blog post

**Comment by s-utstrand** [comment]
Not sure if it's possible to modify the template for the blog post, so this might not be possible. After a quick google search and checking the docusaurus documentation, I couldn't find anything on this. Do you know if this can be done, @jonny-wg2 ?

**Comment by torotimes** [comment]
> Not sure if it's possible to modify the template for the blog post, so this might not be possible. After a quick google search and checking the docusaurus documentation, I couldn't find anything on this. Do you know if this can be done, @jonny-wg2 ?

@jonny-wg2 is out on parental leave. Perhaps @david-wg2 or @mtl-wgtwo could take a quick look?

**Comment by david-wg2** [comment]
I can have a look 👀

**Comment by david-wg2** [comment]
Unfortunately, this doesn't look very straightforward. The platform we've built the webpage on is intended for technical documentation (not creative websites/blogs), and the blog we currently have is enabled through a blog plugin. This plugin has limited configuration options.

**Comment by torotimes** [comment]
Hey @david-wg2 thanks for looking into this! Ok, then I think we archive this issue. It's not a critical one ATM. 

But in general, we do want to "convert" a casual reader into learning more about us or exploring other content. So we'll keep exploring opportunities for doing that on our site. 

@s-utstrand I will then archive this issue. Thanks for exploring.

**Comment by david-wg2** [comment]
I've asked a question in the Docusaurus discord, I'll update if I get an answer.

**Comment by david-wg2** [comment]
They say you can change `BlogPostItem` by "wrapping" it: https://docusaurus.io/docs/swizzling#wrapping

**Comment by s-utstrand** [comment]
> They say you can change `BlogPostItem` by "wrapping" it: https://docusaurus.io/docs/swizzling#wrapping

Ah, that seems to be the trick. Thanks, @david-wg2 
Should be a pretty easy fix then, so you can probably re-open the issue @torotimes

**Comment by torotimes** [comment]
Reopened it now.

**Comment by david-wg2** [comment]
> Ah, that seems to be the trick. Thanks, @david-wg2

 You are most welcome, sir!
