### ISSUE TITLE
Feature list and early beginnings of a "Reverse RFP"

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#197]
Hey @Prid13 - this is a potentially big one for ya. 

Have a look at the project description here. You have received access to it. 

https://docs.google.com/document/d/1dtWzBPKMtpzJMchNnURtTZbQwIv2Of45aqYVNrjWsNc/edit

When you've read it, let us know and we'll talk about it to ensure we're relatively clear on the assignment.

**Comment by Prid13** [comment]
Hey, so I just finished the initial sketch of how I thought this could look like:

![Screenshot_508](https://user-images.githubusercontent.com/27897747/204587800-91892b65-cbf4-4aba-b8db-b6fe0571e48a.png)

-----

![Screenshot_509](https://user-images.githubusercontent.com/27897747/204588319-51dc0dd2-839d-47a9-8273-3d03587f20d5.png)

-----

![Screenshot_517](https://user-images.githubusercontent.com/27897747/204588477-69adf433-0194-4b70-b0ec-a33ff372a0d8.png)

Thoughts? :)

The development of the single entry template is also close to finishing. I'm trying to make this as simple as possible for anyone to add new entries. The working solution so far is to have Markdown pages (.md) to create the single pages for the individual features, and additionally having a single file with _all_ the features listed (that affects the Features List page, e.g. order of features shown) which also maps to the individual pages they lead to.

As for the hover-over functionality, will there be a lot of text in the tooltips, or just a simple one-liner explaining the acronym? :)

**Comment by torotimes** [comment]
Hey @Prid13 - we are starting to get texts ready (see the second column here with short descriptions). Wanna start making those individual pages? This will be a bit of a job for you, perhaps!

https://docs.google.com/document/d/1dtWzBPKMtpzJMchNnURtTZbQwIv2Of45aqYVNrjWsNc/edit
