### ISSUE TITLE
Blog: Should we allow for comments under our blogs? 

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#20]
Pro: We come across as a more open and transparent company. 
Con: This requires moderation and follow-up (we need to respond to comments and questions). 

My view: We should consider doing this at a later stage.

**Comment by jonny-wg2** [comment]
Personally, I believe comments will be spammy and not so beneficial to have cmments. Perhaps something like the medium claps could be fun to have https://github.com/Kikobeats/react-clap-button

**Comment by torotimes** [comment]
That's a good point. It might get spammy. 

But note that posts like the one by Seb on specs behind the specs had more than 100 comments on Hacker News. So there might be something to tap into here. 

My take: This is not a priority now (comments or claps) versus other development projects. So maybe we just save this for the future?

**Comment by jonny-wg2** [comment]
Perhaps updating the blog to link to the hackernews post could be cool?

**Comment by torotimes** [comment]
Yeah, that could work.

**Comment by torotimes** [comment]
We can close this issue for now
