### ISSUE TITLE
Add conversion support for web form submission

### ISSUE THREAD

**Issue by jonny-wg2** [working-group-two/wgtwo.com#200]
The goal is to enable conversion tracking. When a user sends a message, append `?send-message-success` to the URL.

Today, we have several places where users can submit messages, for example, https://www.wgtwo.com/contact/ or https://www.wgtwo.com/security/ or https://www.wgtwo.com/case-studies/

User journey:
1. user navigates to one of the sites to submit their details to get in touch with us
2. when the user clicks send message the browser reloads with `?send-message-success`. Eg. www.wgtwo.com/contact?send-message-success

Note: open for ideas on how to best implement this - but in theory we need an URL endpoint that is called.

**Comment by Prid13** [comment]
@jonny-wg2 I see that the messages are sent by [calling a URL endpoint pointing to a Slack hook](      "aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDdCOTlMQkRNL0IwMzEwRjYxVUNDLzNsU0xVQVJmWk52YWlubXpKT0VUUEVGdAo="). Is a bot perhaps being called via this endpoint? If so, wouldn't appending the extra tracking param to _that_ URL be better than redirecting the user to a page with that extra param appended client-side?

I am NO expert at these things, but this is the first thing I thought of. I feel like client-side "tracking" is prone to error as people could reload the page _with_ the param appended, someone could share the link _with_ the param appended, etc., giving lots of false positive (or in my imagined edge cases, hehe).

If the Slack bot is able to handle extra URL params, then perhaps we should just internally call the fetch function with pre-defined tracking params on each form submission, or what do you think? :)

The Slack bot could perhaps further call another API to easily store the data. But again, I have no experience with tracking, so excuse my naïveté 😅

**Comment by torotimes** [comment]
@jonny-wg2 do you have a sec to look at this? :)

**Comment by jonny-wg2** [comment]
We can actually close this issue. After digging more into GA4, they have a new dashboard / insight called "form_start" which has the information I was actually looking for! :)
