### ISSUE TITLE
Design a product roadmap for /product-ecosystem

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#201]
Hey Zain

New one for ya. 

We're going to build a product roadmap graphic for https://www.wgtwo.com/product-ecosystem/

Imagine an overview of 50 products - under 5-6 categories. 

We're open to how we execute it, but one way of thinking about is how they do it in a shopping app like Oda, where you first hit categories then get an overview of the available products. Or everything on one page. 

Here's an overview of our roadmap, but we're working on how it's organized. 
https://docs.google.com/document/d/1UITxL8WV9kwR-5o-thOJqei_NpwleVlIssEdI-timjk/edit

I need to explain this to you a bit further. Let's talk on video/phone today or tomorrow?

**Comment by torotimes** [comment]
Here's one example of how Dovetail sets up their roadmap (although this is for features, not products). 

It's a nice way of getting everything on one page! 

https://www.notion.so/07a1f771e177426bb1e224add5dcf4e4?v=cb917ecfdc5047d99652de7415eb5b88

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/98818609/206450693-5681c05f-047e-471e-b93e-617320917e4a.png">

**Comment by torotimes** [comment]
@Prid13 can you give this one priority - along with the one about features / reverse RFP?

**Comment by torotimes** [comment]
Hi @Prid13 

Check out this document. It contains the actual categories and list items under each. 

https://docs.google.com/document/d/1Ou-wGfNFaufkGvcpMrv_waGF1gWqGdrmmnBGccwl5fE/edit

Also, we discussed the placement of this roadmap today. It should go here, under the main heading and first paragraph. See arrows. 

<img width="786" alt="image" src="https://user-images.githubusercontent.com/98818609/207899088-c6bcf895-da0a-4d14-a61e-7462e4dee2b0.png">

**Comment by Prid13** [comment]
@torotimes Awesome! What does the last part about **Interaction** mean?

So, when you click on a Roadmap item, a popup box with some more info should be shown, right? Should there be a link included in there that's different for who's visiting the page?

Here's the development so far:

![image](https://user-images.githubusercontent.com/27897747/208127177-6994595a-29ff-4345-940d-ec292030524c.png)

And the best balance I could find between simplicity and programmer-friendliness was this way of storing the info:

> <img src="https://user-images.githubusercontent.com/27897747/208127436-cf4fd5e1-0a6a-4469-a726-e8f6e709f7b7.png" width="500">

**Comment by torotimes** [comment]
Hey Zain!

Trying to keep this as clear as possible:

**1. Change the order of the columns from left to right - also see the slight rewriting of the first one:**
- Products on our radar
- Backlog
- Coming soon
- Live

**2. When you hover-over or click a box**
- Name (like you have now)
- Short description
- Source 

Example:
> Smart & Personalized Voicemail
> Read your voicemail and custom-greet your contacts 
> ([Voxist](https://www.voxist.com))

**3. Interaction**
By this we mean that below the roadmap we should have two CTAs (call to actions). 
- Operators: Talk to us about differentiation and revenue growth  (link to contact form)
- Developers: Drive distribution and monetize your products

**4. Maintenance**
Your storage system looks meaningful but I haven't looked at it deeply yet. I'm sure we'll be able to edit column contents!

🙌

**Comment by Prid13** [comment]
@torotimes your concise way of describing and knowing exactly what to write for me to understand and proceed is just on a whole another level 🙌💯 And the formatting is top-notch as well 🌟

The Roadmap feature is DONE: https://github.com/working-group-two/wgtwo.com/pull/205

The reason why it took so long is because it was 10% implementing the feature, and 90% fighting with libraries, tweaking the design, and fixing bugs. I swear, finding a suitable library is harder than finding pure gold it almost seems... 😅

Idk if the roadmap looks good enough on mobile, which is why I thought of Collapsible Sections (Accordion) in mobile view. Could that be necessary -- what do you guys think? :)
