### ISSUE TITLE
Create a newsletter sign-up page

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#204]
Hey @Prid13 

Can you create a separate page:

wgtwo.com/newsletter-signup

The component is available on the front page:

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/98818609/208674945-47f8de17-2f7a-4e21-b6f0-35680a1a3097.png">

Any questions? Please shoot!

(by the way, we may already have this page, but I'm not sure where in case).

**Comment by torotimes** [comment]
Hey @Prid13 wanna get started with this one?

**Comment by Prid13** [comment]
@torotimes I'm just finishing up the Features page (Reverse RFP), so will get to this asap after that 😇

**Comment by torotimes** [comment]
excellent. thanks so much, Zain!

**Comment by Prid13** [comment]
(Wrote this last night but totally forgot to post, so posting it now. Excuse the outdated info 😅)

Done: https://github.com/working-group-two/wgtwo.com/pull/211

The almost-identical page was the [Contact Us/Talk to Us page](https://www.wgtwo.com/contact/) (scroll down to see the newsletter component).

But I made a new page `/newsletter-signup` :)

Questions:
- Do you want it linked to some button somewhere?
- Is the design okay? (whipped it up pretty quickly...)
- Anything else to add to the page? :)

Thanks for the patience 😇
