### ISSUE TITLE
Fix "meta image" or whatever the hell it is called

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#213]
Hey @Prid13 , can you look into this?

When we share content from our pages it includes a big-a** company icon and wordmark. 

Like this here:

https://twitter.com/WorkingGroupTwo/status/1612453969091260421

<img width="639" alt="image" src="https://user-images.githubusercontent.com/98818609/211330265-2093e091-27a8-41df-9a0c-de0e7439180d.png">

Or on Slack:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/98818609/211330447-3f37279c-e51a-4169-aa0f-96218e5c264b.png">

Is there a way we can change this "meta image" or what they call it?

**Comment by torotimes** [comment]
Hey @Prid13 can you help me with uploading the images? I don't know how to do this. 

See some logos here
![wgtwo-portrait-farger](https://user-images.githubusercontent.com/98818609/212093033-d03ce60b-37d7-4905-a248-18cc40a82232.png)

**Comment by Prid13** [comment]
@torotimes Does this look good enough? Or do you want it smaller? Or some additional text or flair added to it? :)

![image](https://user-images.githubusercontent.com/27897747/213536909-34f37765-ba94-4722-b368-3755684a4124.png)

**Comment by torotimes** [comment]
it still feels really big to me. 

Test it by making a post on twitter or linkedin, using a link like this one:
https://www.wgtwo.com/blog/mobi-expansion-with-wg2-aws/

**Comment by Prid13** [comment]
https://github.com/working-group-two/wgtwo.com/pull/228

**Comment by torotimes** [comment]
Closing this one for now
