### ISSUE TITLE
Update platform traffic

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#225]
Hey @Prid13 

Can you update the platform traffic figures on this page? 
https://www.wgtwo.com/technology/

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/98818609/213658229-cc9d8d91-8e93-4b83-8329-49c169a1e970.png">

New figures:
SMS: 156 million
Voice calls: 354 million
MMS: 32 million
Data uploaded: 3.07 PB
Data downloaded: 30.1 PB
Connectivity events: 418 Billion

Thanks!

**Comment by Prid13** [comment]
https://github.com/working-group-two/wgtwo.com/pull/229

Are you sure SMSes are **156 million**? Just making sure 😅

**Comment by torotimes** [comment]
Yes, that's correct.

Thanks for the edits, I have approved and merged.

**Comment by torotimes** [comment]
Thanks, @Prid13 !
