### ISSUE TITLE
Update partner logos on frontpage

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#226]
Hallo @Prid13 

We have a new customer - and we'd like you to add it to the overview on the front page. 

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/98818609/213721189-184afeee-f677-42ee-b2d6-c3a06ee33f60.png">

I attach the logo. 
![Mobi,_Inc _logo](https://user-images.githubusercontent.com/98818609/213721301-8fb19dd1-6bbf-4b42-bfd8-9f3064500189.png)

Takk!

**Comment by Prid13** [comment]
https://github.com/working-group-two/wgtwo.com/pull/227

**Comment by torotimes** [comment]
Hi @Prid13 

I approved and merged this one, but we have a few edits:

1. Remove the logo called "Enghouse Networks"
2. Increase the size of the Mobi logo to match that of Telenor next to it
3. Replace the "eRate" logo with Telavox. See below. 

![telavox](https://user-images.githubusercontent.com/98818609/214008513-dcd39052-3195-44e5-bfab-c193657c3bdf.png)

**Comment by Prid13** [comment]
https://github.com/working-group-two/wgtwo.com/pull/230

**Comment by torotimes** [comment]
Hey @Prid13 

Can you add this Kyocera logo to the logo overview on the front page please?

![Kyocera_logo svg](https://user-images.githubusercontent.com/98818609/216926779-df02961f-ca5c-47be-8f1f-6014d0fb2560.png)

Can you squeeze it in between MKI and Atos on the bottom level?

**Comment by Prid13** [comment]
Done: https://github.com/working-group-two/wgtwo.com/pull/243

**Comment by torotimes** [comment]
Thanks - good to go, @Prid13 . I have merged it!
