### ISSUE TITLE
Improve regex for contact form

### ISSUE THREAD

**Issue by jonny-wg2** [working-group-two/wgtwo.com#231]
Problem: We receive malicious / spam messages that include code. 
```
Message from [wgtwo.com/contact](http://wgtwo.com/contact)
Name: s"><img src=x>${{8*8}}http://somewebsite.com/
Email: [solankiajay0808@gmail.com](mailto:someemail@gmail.com)
Company: s"><img src=x>${{8*8}}http://somewebsite.com/
Message: s"><img src=x>${{8*8}}http://somewebsite.com/
```

Goal: Prevent such above messages via regex

Goal is to add client-side regex to **not** allow messages to be sent if one or more `<` or `>` exists in any field (name, email, company, message). We have something similar for ensure an email is an email, so it would be extending this.

**Comment by torotimes** [comment]
Assigning this one to @Prid13

**Comment by Prid13** [comment]
Done: https://github.com/working-group-two/wgtwo.com/pull/235
