### ISSUE TITLE
Update blog layout

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#233]
Hi @Prid13 

Here's a new one for ya. 

Our blog today features a column to the left where all historical posts are listed. This is starting to look a bit messy now. When you click a post to read it, the column follows along. 

Can you experiment with:

**1. Removing the left column from posts, e.g. like this:**

![image](https://user-images.githubusercontent.com/98818609/214867160-994c66c9-6252-4740-8f15-510f8654fc90.png)

**2. Rearrange the content on the blog front page ( /blog) to look more like a news site.** 

It could be something like this:
https://preview.themeforest.net/item/nimbo-personal-wordpress-blog-theme/full_screen_preview/22867641?_ga=2.167439932.384548502.1674744908-1135655641.1674744908

Or this:
https://preview.themeforest.net/item/hcode-responsive-multipurpose-wordpress-theme/full_screen_preview/14561695?_ga=2.140633264.384548502.1674744908-1135655641.1674744908

Please note: We don't have a lot of images for all our posts, so it's important that IF we choose a news site layout, we need to not rely on having images. Some posts don't have images at all. Wanna have a look at some options? Put your designer to work! :)

**Comment by Prid13** [comment]
This was fun 😇⭐

Tested 2 layout designs:
1) 3-Grid Column Cards
2) Single Column News Feed

# 3-Grid Column Cards
![Screenshot_3800](https://user-images.githubusercontent.com/27897747/215292316-d9316fcb-420b-445e-ae78-c64c534a9cde.png)

- Removed some of the icons and info to minimize the content
- The main problem is that the Titles are tooooo long for this to effectively work 😅

**Here's with _everyting_ still intact:**
![Screenshot_3792](https://user-images.githubusercontent.com/27897747/215292340-18b1e74a-eb38-4373-9f9a-f8a4a6c4807e.png)

### Videos:

https://user-images.githubusercontent.com/27897747/215292371-777c7896-a747-49b1-88bb-edd8c11b59f9.mp4

https://user-images.githubusercontent.com/27897747/215292376-cb3b1d37-a94b-4690-9e10-cf5260a70e53.mp4

# Single Column News Feed
![Screenshot_3789](https://user-images.githubusercontent.com/27897747/215292434-8e4d97e1-6efa-40f5-b60f-5bc4d917fbb2.png)
![Screenshot_3790](https://user-images.githubusercontent.com/27897747/215292435-43c32e37-5054-4130-92cb-09d46da94390.png)

- Looks cleaner with all the info still there
- Harder to get an overview of all the recent posts

### Video:

https://user-images.githubusercontent.com/27897747/215292483-67619434-cd67-453a-b780-1bd5f095ad01.mp4

----

If the multi-column card layout is desired, then what "unnecessary" info can we shave off to make it look cleaner? :)

**Comment by torotimes** [comment]
really good work with this, @Prid13 ! 

(hey, @jorunfa, you should take a look at this, too). 

Zain, I think we should try to figure out a way to use the 3-column grid system for the /blog front page. What if we made a rule that a headline basically cuts off after XX characters? So a longer one will be cut off by (...) ? That's one way to solve it, at least. 

I don't think we need the sharing buttons or tags in the 3-column grid. 

Do we need the content above the truncate in the 3-column grid? Maybe, it does look fairly good. 

Thoughts?

**Comment by jorunfa** [comment]
Ellipsis are an option. FYI, that would be something like:
```
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 2;
    overflow: hidden;
```

(i just happened to have that in my clipboard, actually)

But I'm slightly torn between 1 and 3 column card setup. 3 looks better, but 1 serves the content (and our long ass headings) better. Would be interested in seeing how it looks with the ellipsis.

Maybe up to 5 lines of heading on cards without header images?

**Comment by jorunfa** [comment]
I think I'd limit tags to one line as well, and `align-items: baseline` on the container holding tags and the read more button, so they're aligned, maybe.

**Comment by jorunfa** [comment]
For me: I think we most def should have the teaser text in the cards. The use case/important thing is not to have an overview of _all_ articles, but rather that you find a _recent_ one that's interesting and catches your interest.

**Comment by jorunfa** [comment]
If the tags are chips, do you need the `Tags: ` label? I'd like to see how it looks if you remove that and clamp the tags to one line, and align it with the read more button.

**Comment by torotimes** [comment]
> For me: I think we most def should have the teaser text in the cards. The use case/important thing is not to have an overview of _all_ articles, but rather that you find a _recent_ one that's interesting and catches your interest.

I'm with you on that one. Agreed.

**Comment by jonny-wg2** [comment]
Love the layout! Great improvement to the existing setup! 💯

I like the grey background with the white article like in the image. Would it make sense to also make this the new default layout for viewing a single blog post in full page? 

<img width="876" alt="image" src="https://user-images.githubusercontent.com/39831372/215500878-c9f232c8-6515-44df-9872-25e2f96c5889.png">

**Comment by Prid13** [comment]
@jorunfa Super coincidence :D! Thanks for all the handy tips and tricks, appreciate it ⭐

@jonny-wg2 Awesome, thanks 😇! I'm guessing you want the 1-column layout for the Blog overview as well? What are your thoughts on the 3-column grid? When clicking on "Read more" the user could be directed to the new single post layout, perhaps?

**Comment by Prid13** [comment]
I gave it my all with this one:

![Screenshot_3960](https://user-images.githubusercontent.com/27897747/215971395-a4deca14-3317-45c7-9239-5147e873bc1f.png)

---

![Screenshot_3958](https://user-images.githubusercontent.com/27897747/215971404-0a93f94e-bf87-44a8-a886-6a4962b837b1.png)

![Screenshot_3959](https://user-images.githubusercontent.com/27897747/215971415-e7329188-9e93-4896-9f90-f885408ce16c.png)


https://user-images.githubusercontent.com/27897747/215971506-47e6562f-950f-4dcb-b2dd-44fcb1a4698b.mp4

---

Thoughts? :)

**Comment by jorunfa** [comment]
I think it looks quite good!

1.
I'm no designer, so take this with a grain of salt, but I'm wondering how it would look with more things aligned on a single vertical line on the left side of the card, or two at the most (i.e. eliminating gap 1 and perhaps 2):

![image](https://user-images.githubusercontent.com/1413275/215985629-37ab4ffb-b8c6-489a-a1f9-5f8b4bdef07f.png)

2.
I also like that the read more buttons are easy to spot. Small concern: how do they look like hovered/with keyboard focus?

**Comment by jonny-wg2** [comment]
> @jonny-wg2 Awesome, thanks 😇! I'm guessing you want the 1-column layout for the Blog overview as well? What are your thoughts on the 3-column grid? When clicking on "Read more" the user could be directed to the new single post layout, perhaps?

I think we can use both layouts, 3 columns when on web and on mobile we switch to the 1 article.

----

Great work!

+2 on @jorunfa 's suggestion with the alignment - small fix.

Great improvement though from what currently exists!

**Comment by torotimes** [comment]
Good comments, @jorunfa and @jonny-wg2 ! Thanks

Zain, I think we should go for the 3-column layout on desktop. How about keeping all headlines in the same font size and just cut them off as you do it here? We can start using shorter headlines as a general rule. 

Wanna make these changes and go for the PR?

**Comment by Prid13** [comment]
@jorunfa thanks for the feedback. Here's a quick mockup, what do you think? :)

![wgtwo blog cards mockup](https://user-images.githubusercontent.com/27897747/216870163-fea524ae-42c0-43e8-85af-96f31316812e.png)

---

@torotimes I'd really like to start implementing this, but I hit a roadblock not knowing how to deal with a blog card _with_ image next one _without_ (screenshots are from before the changes above were made):

![Screenshot_4005](https://user-images.githubusercontent.com/27897747/216870756-6465336b-46bc-4058-be58-45b8948adf36.png)
![Screenshot_4002](https://user-images.githubusercontent.com/27897747/216870760-07ced8a5-a205-451f-8921-65a289a40345.png)
![Screenshot_4003](https://user-images.githubusercontent.com/27897747/216870770-ff2ccd92-a2f8-400a-9888-f8cd68dbdda3.png)

Does it look ... good enough?

I tried making evening out the heading levels like this:

![Screenshot_4001](https://user-images.githubusercontent.com/27897747/216871034-c4bb9b3d-9ef2-4dfc-baf6-22c0d3cb14b6.png)

But that looks weird, and it's going to be chaotic with these mixed in with the normal-sized image-less cards in other rows, not to mention hard to pull of programmatically. Thoughts? :)

**Comment by torotimes** [comment]
Hey @Prid13 (and @jorunfa) I think we will just need to constitute a rule that we always have an image above the truncate going forward. The historical posts are the way they are. 

I think we just pull the headline up to the top of the "box"  and that's ok (but of course not perfect).

**Comment by jorunfa** [comment]
My opinion: I'd go for a placeholder/generic image, maybe just some gray-to-gray gradient or a wgtwo logo for the cards without pics

**Comment by jorunfa** [comment]
I like the new cards better!

![image](https://user-images.githubusercontent.com/1413275/216989436-7f52afad-ba2c-4fca-b6e0-b8e30aa840f0.png)

just one naughty boi here

**Comment by Prid13** [comment]
> My opinion: I'd go for a placeholder/generic image, maybe just some gray-to-gray gradient or a wgtwo logo for the cards without pics

I agree with that. What do you think @torotimes ?

> I like the new cards better!
> just one naughty boi here

Thanks 😅🌟

**Comment by torotimes** [comment]
I agree with the placeholder/generic image. Let's go for that. 🔥

Wanna issue the PR?

**Comment by Prid13** [comment]
> Wanna issue the PR?

So, those images were just design mockups, pure "photo editing" 😅 Turns out there's a lot more pain involved trying to implement the layout changes, hehe. Gonna have to need some more time for this :)

**Comment by torotimes** [comment]
Woooot! It wasn't real code? 

😅 

Maybe I should have figured that. 

How many hours do you think you need for this?

Tor

**Comment by Prid13** [comment]
@torotimes It's DONE :D

### [Live Demo](https://wgtwo-dev.netlify.app/blog/) | [PR](https://github.com/working-group-two/wgtwo.com/pull/247)

> Woooot! It wasn't real code?

Technically, it was _live editing_ on Wgtwo's page by using Chrome Dev Tools (F12, or CTRL+SHIFT+I), but who knew actually _implementing_ those changes in the source code would be such a pain in the behind 😅 The library used to generate wgtwo's website had a complicated setup for the blog layout scattered across dozens of tiny components, and had me manually override each and every single one of those components to make this work. That wasn't a fun experience, haha, but I'm soo glad it's actually done and it's working TuT

The only thing missing is mobile responsiveness, so pls check for bugs and give me feedback on what needs improvement :)

**Comment by torotimes** [comment]
@Prid13 

regarding /blog

One more thing: Can we get "infinite" scroll instead of having to click to the next page after only 9 posts? Alternatively, double the amount of posts before you have to click for older posts?

**Comment by Prid13** [comment]
> "infinite" scroll

I thought about that, but as it stands, the library being used to power the website and the blog is a bit limited on that front. I've already "hacked" it a lot visually to get that blog layout redesign to work, but infinite scroll will unfortunately be a very difficult task, and I don't know what the SEO implications would be 😅 I hope page buttons are okay for now :)
