### ISSUE TITLE
Experiment with front page layout (hero section)

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#236]
Hi @Prid13, here's a new one for ya. 

Let's experiment with layout for the front page hero section (the stuff you see on desktop before you scroll). For now, we don't have a graphic to go with the headline, so let's play with what it can look like without a graphic. 

It could be something, like this, for example, but with different words (see below) 

<img width="537" alt="image" src="https://user-images.githubusercontent.com/98818609/215329291-d26340b4-cb03-4db8-ae9c-f7f090001f33.png">

Here are two new copy variations for you to play with. Note that we should only have one call to action (not two buttons as today). 

### **1.** 
Headline: 

> Plug into the world's mobile core network

First paragraph: 

> Join a league of global telco front-runners in their pursuit of growth and efficiency. By connecting to our borderless core, you will simplify operations, reduce cost by 30-70% and get access to a product marketplace to help you differentiate and build new revenue streams. 

Call to action:

> Show me how 
> (link to https://www.wgtwo.com/request-demo/)

### **2.** 
Headline

> What if you could simplify your mobile network _and_ grow your revenues? 

First paragraph:

> Here’s how: By plugging your network into our global mobile core you simplify operations, reduce cost by 30-70% and get access to a product marketplace to help you differentiate and build new revenue streams. 

Call to action:

> Show me how 
> (link to https://www.wgtwo.com/request-demo/)
>

**Comment by Prid13** [comment]
Cool mockup ⭐! Liked the dark mode with the blue heading. Hopefully changing the color scheme wasn't part of this issue 😅

> ![Screenshot_3862](https://user-images.githubusercontent.com/27897747/215853719-2361386d-9e3a-4a03-800a-f720d219fc6f.png)

<sup>- sorry ¯\\_(◔◡◔)_/¯</sup>

# 1.
![Screenshot_3873](https://user-images.githubusercontent.com/27897747/215852265-77c6f56d-a18e-4f3c-9ac3-c3f3facf4e4e.png)


# 2.
![Screenshot_3875](https://user-images.githubusercontent.com/27897747/215852290-c270d9d0-8cb4-4bdb-be05-18259aea7baf.png)

More width to have the sub-heading in one line:
![Screenshot_3878](https://user-images.githubusercontent.com/27897747/215853699-766edbad-df95-4854-a6d7-7aca1c002542.png)

**Comment by torotimes** [comment]
Hey,

comments:

1. Delete the "Programmable. Scalable. Innovative." as the top headline. Sorry for the misunderstanding. 
Headline: "What if you could simplify..." etc
First para: "Here's how..." etc

2. Call to action button: Show me how (not How)

3. Go for the narrower width (as in your #1 and #2) (not #3)

**Comment by torotimes** [comment]
omfg what happened there? haha

3. Go for the narrower width (as in your 1. and 2.) (not 3.).

**Comment by torotimes** [comment]
Hey @Prid13 - will you take a look at this one? See above.

**Comment by Prid13** [comment]
@torotimes

### Have a look at the first live experiment: https://wgtwo-dev.netlify.app/

---

![Screenshot_4129](https://user-images.githubusercontent.com/27897747/217123801-d47ff40f-7537-4dad-a550-031936c7e29c.png)
![Screenshot_4130](https://user-images.githubusercontent.com/27897747/217123805-f98587dc-f634-4e18-b7a6-8c04a65f9ef4.png)
![Screenshot_4131](https://user-images.githubusercontent.com/27897747/217123794-b8a4411b-a0fa-4e55-9ffc-af590382f877.png)

# Other concepts

![Screenshot_4134](https://user-images.githubusercontent.com/27897747/217124837-079e32e6-2787-40fd-88c2-0560e9791eb9.png)
![Screenshot_4115](https://user-images.githubusercontent.com/27897747/217123926-cfbe1ff6-242f-4e52-8eea-636c080f30f3.png)
![Screenshot_4114](https://user-images.githubusercontent.com/27897747/217123930-da0f8c76-4567-48e0-98f3-f4f527821c56.png)
![Screenshot_4120](https://user-images.githubusercontent.com/27897747/217123979-ed739fc7-c0dd-4110-a39c-628343abf446.png)
![Screenshot_4117](https://user-images.githubusercontent.com/27897747/217123984-de4af913-fc03-4e3a-bbbc-605834f44e88.png)

## Why not animated?


https://user-images.githubusercontent.com/27897747/217124064-311bcae9-96bf-453f-b87f-1d322840e1a8.mp4

https://user-images.githubusercontent.com/27897747/217124857-1458f8b6-8e67-44cc-b30c-0d38f328f10a.mp4

**Comment by Prid13** [comment]
@torotimes Here you go: https://wgtwo-dev.netlify.app/ | https://github.com/working-group-two/wgtwo.com/pull/244

This overrode the Blog Layout Redesign PR though for the dev-page, so whenever you'd like to change the active PR on the dev-page, 1) REMOVE the `devpages` label, 2) CLOSE the dropdown (so it registers the deselection), and 3) ADD the `devpages` label -- that will trigger a re-deployment :)

**Comment by Prid13** [comment]
Btw, when checking out the dev-page, you can easily test different colors in your browser (changes are temporary and will be removed once you refresh):

https://user-images.githubusercontent.com/27897747/218110296-9b83d0ec-31a8-4ea3-8271-c7c60a6a2a90.mp4

😇⭐

**Comment by torotimes** [comment]
I merged it! Let's see how it flies!

Thanks for working on this.

**Comment by Prid13** [comment]
> I merged it!

WOAH!! Bold move 👏🙌👍

**Comment by torotimes** [comment]
Ja, men jeg ser nå at CTAen ikke gir helt mening (og det er min feil ikke
din)

Vi skriver "Show me how" - og da hadde jeg nok egentlig ventet en slags
online demo, ikke at du blir sendt til et skjema.

Skal prøve å jobbe med dette til uken.

TAkk for bra jobbing!

Tor

**Comment by Prid13** [comment]
Null stress, jeg liker innsikten og "selvkritikken" du har, det er imponerende 👏 Takk, i like måte ⭐😇

**Comment by torotimes** [comment]
Closing this one for now.
