### ISSUE TITLE
Update SMS figure

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#239]
Hei @Prid13 - can you update this figure on /technology ?

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/98818609/215766244-d33502cf-2bcf-4489-9cd9-5c9dfc1729f7.png">

The number for SMS is
`527 million
`

Takk!

**Comment by Prid13** [comment]
I guess that number _was_ incorrect after all 😅 [Fixed](https://github.com/working-group-two/wgtwo.com/pull/240) 🙌
