### ISSUE TITLE
Contact page: Add office addresses back into https://www.wgtwo.com/contact/

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#24]
Perhaps just add it under the contact form?

**Comment by torotimes** [comment]
Add:

Sommerrogata 17
0255 Oslo
Norway

**Comment by gi-wg2** [comment]
Address to the Trondheim office would be
```
Working Group Two
c/o Digs
Krambugata 2
7011 Trondheim
```

**Comment by torotimes** [comment]
Jakobsbergsgatan 8
c/o ABCD 1st floor
11144 Stockholm
Sweden

**Comment by jonny-wg2** [comment]
I added the addresses in the docs. This is easiest so it can be updated by everyone.

www.wgtwo.com/contact
![image](https://user-images.githubusercontent.com/39831372/154692382-5a85d3f8-8f50-467d-ab3a-175eefed45a8.png)

![image](https://user-images.githubusercontent.com/39831372/154692511-35ac0481-f780-42fd-9838-b3c838fb6b59.png)



www.wgtwo.com/docs/about/offices
![image](https://user-images.githubusercontent.com/39831372/154691371-7fe1b0ce-0d0a-458c-ac74-e55e737a4827.png)
