### ISSUE TITLE
I can't install sharp on windows 10

### ISSUE THREAD

**Issue by victor-alf** [working-group-two/wgtwo.com#252]
node version v18.14.1

error D:\wgtwo.com\website\node_modules\sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: D:\wgtwo.com\website\node_modules\sharp
Output:
sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-win32-x64.tar.br
sharp: Installation error: aborted

**Comment by torotimes** [comment]
I'm not sure what the context is here, so closing the issue.
