### ISSUE TITLE
fix blog cards issue in Safari on Mac

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#253]
hi @Prid13 

When you run /blog on Safari on Mac, you get a display issue. 

![image](https://user-images.githubusercontent.com/98818609/219612383-7f23d979-4f1e-41bf-964d-d98ae829b88a.png)

The same goes for 
<img width="349" alt="image" src="https://user-images.githubusercontent.com/98818609/219612495-63968fab-95bc-49e7-85c2-675917d8d9c5.png">

Yan, nne of our guys said (on Slack):
a workaround is to remove the display: css entry in articleCardContent_XsZ2 stuff

![image](https://user-images.githubusercontent.com/98818609/219612599-b6ab9675-d597-43bd-ad4e-bfa56277f220.png)

But is that the right approach? We shouldn't get very long cards. 

Please have a look.

**Comment by Prid13** [comment]
Ah, I feared this would happen :( This is most likely because the code I'm using to "hide" longer content, [as suggested by jorunfa](https://github.com/working-group-two/wgtwo.com/issues/233#issuecomment-1408469686), is non-standard, and there's no guarantee it will work on all browsers.

@jorunfa what do you think? :)

**Comment by jorunfa** [comment]
https://github.com/working-group-two/wgtwo.com/pull/254

**Comment by jorunfa** [comment]
Actually I see some more issues with the card. Think it might be related to display: flex on some parent. I'll try to fix that too before merging.

**Comment by torotimes** [comment]
Thanks so much for looking at this, @jorunfa.

What's your take on the general card design input in the slack channel? David made the point that we should perhaps make the cards (without images) darker.
