### ISSUE TITLE
mini fix

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#266]
Hey @Prid13 

Can you fix this little error - here https://www.wgtwo.com/careers/

See "Leverage" - it should be "leverage"

<img width="704" alt="image" src="https://user-images.githubusercontent.com/98818609/222143077-0335100c-29c8-4f3b-9e9c-b7facf4b45df.png">

Takk!

**Comment by Prid13** [comment]
https://github.com/working-group-two/wgtwo.com/pull/267
