### ISSUE TITLE
Remove Roadmap for now

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#273]
Hi Zain, we're reworking our Roadmap, so perhaps you can just remove this component for now? 

It's at this URL: https://www.wgtwo.com/product-ecosystem/

<img width="418" alt="image" src="https://user-images.githubusercontent.com/98818609/224038117-e6cc1c86-be8d-4283-bfe3-70383475b59d.png">

**Comment by Prid13** [comment]
Done: https://github.com/working-group-two/wgtwo.com/pull/274
