### ISSUE TITLE
Remove sneaky "s" on jp/implementation

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#286]
Hi @Prid13 

Can you delete this "s" from https://www.wgtwo.com/jp/implementation/

<img width="765" alt="image" src="https://user-images.githubusercontent.com/98818609/228166255-c8feb8e0-c8eb-4306-a161-69ddc4d4f7d2.png">

thanks!!

**Comment by Prid13** [comment]
And done: https://github.com/working-group-two/wgtwo.com/pull/288
