### ISSUE TITLE
[css][blog] make the article a tad wider

### ISSUE THREAD

**Issue by jonny-wg2** [working-group-two/wgtwo.com#292]
I find that the blog is a tad skinny and would like to increase the width.

I tried to play around with it and couldn't figure it out 😬 but essentially what I am looking at doing is applying some changes
```
.col--8 {
    --ifm-col-width: calc(9 / 12 * 100%);
}
.col--offset-1 {
    margin-left: calc(0.5 / 12 * 100%);
}
.col--offset-2 {
    margin-left: calc(0.5 / 12 * 100%);
}
```

@Prid13 any tips on how I can achieve this - or if making a pr is easier?

**Comment by Prid13** [comment]
Here you go: https://github.com/working-group-two/wgtwo.com/pull/298 😇
