### ISSUE TITLE
Convert AWS blog post into a WG2 blog post

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#293]
Hi @Prid13 - 

Can you put this entire text (and images) into markdown and issue a PR for our blog (wgtwo.com/blog)? 

Author is Holger Ihrig (who works here, but also some folks from AWS - whom we don't have in our author file). So I think you should just use Holger, but we'll add author names to the others below the truncate. 

https://aws.amazon.com/blogs/apn/how-working-group-two-accelerates-the-creation-of-mobile-networks-with-aws-snow-family/

Let me know if this was clear.

**Comment by Prid13** [comment]
This was clear :)

https://github.com/working-group-two/wgtwo.com/pull/300

**Comment by torotimes** [comment]
Thanks!
