### ISSUE TITLE
[bug][safari][css][contact form][modules] spans off the page when using safari (phone and browser)

### ISSUE THREAD

**Issue by jonny-wg2** [working-group-two/wgtwo.com#296]
Example: 

https://www.wgtwo.com/contact/
<img width="993" alt="image" src="https://user-images.githubusercontent.com/39831372/228818258-3fd35a60-b3bc-4cd6-a590-635b74064c9c.png">

https://www.wgtwo.com/security/
<img width="999" alt="image" src="https://user-images.githubusercontent.com/39831372/228818338-647dc982-db90-4015-8e57-23f3955442fd.png">

Additionally, on the security page there is something weird with safari and these boxes
<img width="975" alt="image" src="https://user-images.githubusercontent.com/39831372/228818460-f2ccb1dd-6665-415f-96d3-2c9ffaeead85.png">

Essentially, this should be the same as what we have on the homepage, so maybe something was changed and not propagating? 
on homepage and working
<img width="879" alt="image" src="https://user-images.githubusercontent.com/39831372/228818623-0e140b17-24ca-4497-90e1-24e0fedf71f8.png">

**Comment by Prid13** [comment]
Sorry I haven't had a chance to look at this. I don't have macOS so I can't test this on desktop (unless you're willing to invest on a MacBook for me 😎), and haven't educated myself (yet) on how to debug in safari mobile browser 😅 But looks like someone else fixed this already, right?
