### ISSUE TITLE
White boxes with white text

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#302]
Hey @Prid13 

Ref this page: https://www.wgtwo.com/security/

Can you fix the issue with the white boxes with the white text?

Thanks so much!

**Comment by torotimes** [comment]
There's text embedded in the boxes, just FYI

**Comment by Prid13** [comment]
Oj, looks like this slipped past in the JP implementation PR: https://github.com/working-group-two/wgtwo.com/commit/1721e84b3699a30692953d009f15504a189bcd1d#diff-ed24295afd2d8053a00fcd59e71ed654fdc709ad7b53fba5a0d94de08a7c823bL87

https://github.com/working-group-two/wgtwo.com/pull/303

**Comment by torotimes** [comment]
Thank, mister!
