### ISSUE TITLE
Minor link issue on /jp

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#304]
Hi @Prid13 

Can you send the button on /jp front page that says sXGP to this link?

https://www.wgtwo.com/jp/implementation/

Thank you!

<img width="267" alt="image" src="https://user-images.githubusercontent.com/98818609/229352955-e585765d-2dfc-4327-ae67-7119554ffc9f.png">

**Comment by Prid13** [comment]
Sorry for the wait, here you go: https://github.com/working-group-two/wgtwo.com/pull/308

Thanks for your patience 😇⭐

**Comment by torotimes** [comment]
Thanks and closing this one
