### ISSUE TITLE
Add new blogpost: product trailblazers

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#311]
Hi @Prid13 

Can you add this newsletter as a blogpost to /blog?

https://docs.google.com/document/d/1iWRxYVdKBzvezUBqtAUYXvw8oTLJ9J9_6O_vRRZyjBo/edit?usp=sharing

(see actual text on page 2)

Skip the action buttons. 

Thank you!

**Comment by Prid13** [comment]
Here ya go: https://github.com/working-group-two/wgtwo.com/pull/314

**Comment by torotimes** [comment]
Thanks, closing this one! nice work
