### ISSUE TITLE
[css][blog] improve blog

### ISSUE THREAD

**Issue by jonny-wg2** [working-group-two/wgtwo.com#320]
I discovered this page which looks very similar to our blog page https://githubnext.com/projects/copilot-for-docs. The goal would be to see what css components we could leverage from this example and enrich our blog to make it look even more pristine. 

A couple of features I noticed
- slight fade on load
- no rounded corners
- more wide blog post
- different background color
- text size grows as the page width changes

![image](https://user-images.githubusercontent.com/39831372/235182791-96fdabf2-ab7e-48f7-a911-aa04e9713f37.png)

**Comment by Prid13** [comment]
Had some free time, so I gave this one a shot:

BEFORE:

<img width="921" alt="Screenshot_6904" src="https://user-images.githubusercontent.com/27897747/235398015-0df18a6f-93f9-4013-949d-1a292a1950c6.png">

AFTER:

<img width="921" alt="Screenshot_6905" src="https://user-images.githubusercontent.com/27897747/235398036-ee1c4065-4449-4cb6-8bb9-d74b62bc65ae.png">

It _does_ look better, especially the extra air and the nicer background color.

With ToC:

<img width="921" alt="Screenshot_6906" src="https://user-images.githubusercontent.com/27897747/235398604-f695867d-8990-4e6f-a284-ded9b4dd962e.png">

---

My only contention is that the extra padding would make the text too narrow and thus showing less text "above the fold":

<img width="921" alt="Screenshot_6909" src="https://user-images.githubusercontent.com/27897747/235399309-815278ae-091b-4804-9fa1-eb7544b3041b.png">

<img width="921" alt="Screenshot_6908" src="https://user-images.githubusercontent.com/27897747/235399331-0f238912-9193-444b-814a-d44be776fd42.png">

But it looks pretty minor in these comparisons 😅 and the edits look much nicer indeed 👍

As for the fade, here's a test animation:

https://user-images.githubusercontent.com/27897747/235401276-143cecaa-2d47-4a26-933a-fd62df5e52a9.mp4

Looks really nice 😇 maybe too nice -- it would leave a lot to be desired for the rest of the website ;)

**Comment by jonny-wg2** [comment]
Wow looks great @Prid13 ! 

Extra padding
- Yeah I see your point here. It looks like the github example https://githubnext.com/projects/copilot-for-docs changes the padding to a smaller size based on the browser max-width.

Fade is subtle but looks great! Adds a "hidden" gem and feeling!

Feel free to craft a PR 💯
