### ISSUE TITLE
Partnership visuals

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#327]
Hi @Prid13 - here's a graphics project for ya, so not a web project as such. 

We'd like to make partnership visuals (basic jpeg/similar formats) to promote our product partners in social channels and elsewhere. 

Use our existing styleguide (for now). 

Here's some inspiration:
![image](https://github.com/working-group-two/wgtwo.com/assets/98818609/86f55110-e8a4-480e-b7a7-b44d35720663)
![image](https://github.com/working-group-two/wgtwo.com/assets/98818609/58d6b1bb-62ed-4b20-90c8-1319eb51ccd4)
![image](https://github.com/working-group-two/wgtwo.com/assets/98818609/f2ede9d8-c696-467a-b7eb-9876c536401c)

Get my drift?

The two companies we'd like you to develop graphics for are:
- i-New
- Truecaller

Here are their websites and logo details:
https://www.i-new.com
https://www.truecaller.com

![image](https://github.com/working-group-two/wgtwo.com/assets/98818609/39761a1a-ae85-4ddb-b44e-0809d762f3e9)
![image](https://github.com/working-group-two/wgtwo.com/assets/98818609/3b489164-3999-4b98-af39-0c03e71c6562)

Do you need more direction or inspo?

**Comment by torotimes** [comment]
@Prid13 do you have time to look at this one? It's a little urgent.

**Comment by Prid13** [comment]
Sorry, just can't seem to make good enough ones. Here's what I've got, but I hate it:

![image](https://github.com/working-group-two/wgtwo.com/assets/27897747/cfbf56bf-2a5f-4f52-ab85-c025b5d28a56)

![image](https://github.com/working-group-two/wgtwo.com/assets/27897747/fe0f6bf4-5d20-45b3-b2a1-42b29e2bcbe3)


![image](https://github.com/working-group-two/wgtwo.com/assets/27897747/5e864d38-7e33-4ea4-9e2c-f42b6fb46ce0)

Also, it's hard to find commercial-friendly free stock images to use 😅

**Comment by Prid13** [comment]
Ugh, I really hate them >,< what's the format of the images, btw? Same as the examples you posted?

**Comment by Prid13** [comment]
Sorry, had to spend some more time making better ones -- couldn't allow myself to ship those:

![inew x wg2](https://github.com/working-group-two/wgtwo.com/assets/27897747/3012968c-09e9-4db3-86a8-d04ec3f1e4bc)

**Comment by Prid13** [comment]
How about these? :)

![wg2 x truecaller - flat](https://github.com/working-group-two/wgtwo.com/assets/27897747/9c85d717-75f9-44db-91c1-897a8d8c0d07)
![wg2 x truecaller - flat blur](https://github.com/working-group-two/wgtwo.com/assets/27897747/0969b9ba-ac90-4447-ac8b-6793e7f5242e)
<img width="444" alt="Screenshot_7690" src="https://github.com/working-group-two/wgtwo.com/assets/27897747/b9e3890c-760f-4e09-bc1c-41360277de99">



![wg2 x inew - flat](https://github.com/working-group-two/wgtwo.com/assets/27897747/eb6dfca9-62b6-45ef-b066-e3d7a67da50b)
![wg2 x inew - flat blur](https://github.com/working-group-two/wgtwo.com/assets/27897747/fd4d6943-a27a-411f-9a7f-bb2191578f9b)
<img width="444" alt="Screenshot_7691" src="https://github.com/working-group-two/wgtwo.com/assets/27897747/0cb35cb4-559a-4ef1-8dd0-294a5f4e3529">

**Comment by torotimes** [comment]
Good to go! Takk, @Prid13 ! Closing the issue.
