### ISSUE TITLE
Improve Features List Design

### ISSUE THREAD

**Issue by Prid13** [working-group-two/wgtwo.com#342]
> @torotimes: "By listing all the features like this, broken into categories, people can get the feeling that we sell these things individually. We don't. And that's the whole point of our platform. You get everything, with no end of life. I'll try to make that message clear on the webpage somehow."

Great observation, couldn't agree more :)

Made a quick mockup of how it can possibly be improved a bit in the presentation:

> <img width="950" alt="Screenshot_7355" src="https://github.com/working-group-two/wgtwo.com/assets/27897747/6c048794-b106-4fcf-995a-d49076571966">

> <img width="950" alt="Screenshot_7359" src="https://github.com/working-group-two/wgtwo.com/assets/27897747/08d0cf00-1061-4332-8134-256f12b8a2ad">

> <img width="950" alt="Screenshot_7360" src="https://github.com/working-group-two/wgtwo.com/assets/27897747/ca8db5b5-8cb2-46a9-9a81-3eaa1d39944d">

https://github.com/working-group-two/wgtwo.com/assets/27897747/c472957d-47b6-4060-84f4-25661e0942f3

Or just "Included Features":

![image](https://github.com/working-group-two/wgtwo.com/assets/27897747/5a38eabf-b695-408b-a985-0832b5f67d9d)

**Comment by jonny-wg2** [comment]
Looks good, I like it better than the boxes!

**Comment by torotimes** [comment]
Ok, great. 

@Prid13 can you use the headline "An all-inclusive mobile core platform"
