### ISSUE TITLE
Fix CSS from branding pr

### ISSUE THREAD

**Issue by jonny-wg2** [working-group-two/wgtwo.com#344]
From the https://github.com/working-group-two/wgtwo.com/pull/318 it introduced some issues on the CSS

<img width="1452" alt="image" src="https://github.com/working-group-two/wgtwo.com/assets/39831372/b494adb6-3779-4cdd-9444-08fe82175599">

<img width="1417" alt="image" src="https://github.com/working-group-two/wgtwo.com/assets/39831372/d48558d6-fc1e-495d-8975-a9c007818659">

There might be other places too - so if we can limit the CSS to only the page that would be great. 

Also the wgtwo.com/brand does not work..

**Comment by jonny-wg2** [comment]
We reverted the PR https://github.com/working-group-two/wgtwo.com/pull/345

**Comment by Prid13** [comment]
Oh right, totally forgot that the brand page was developed with the assumption that it would be on a totally separate "website", i.e. not as part of the Docusaurus framework 😅 Will have to isolate the scope of the CSS

**Comment by Prid13** [comment]
https://github.com/working-group-two/wgtwo.com/pull/349
