### ISSUE TITLE
small edit on /technology

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#351]
This was reported by one of our guys, can you handle, @Prid13 ? Takk!

diff --git a/website/src/features.sidebar.js b/website/src/features.sidebar.js
index d95a974b95..731813d699 100644
--- a/website/src/features.sidebar.js
+++ b/website/src/features.sidebar.js
@@ -148,7 +148,7 @@ export default [
         name: "AMF",
         href: "/amf",
         tooltipText:
-          "The Authentication Management Field (AMF) is a 16 bit value which is used to set the acceptable synchronization window in both the UE (User Equipment) and the network.",
+          "AMF in 5G manages access and mobility. It simplifies processes by separating control and user data and streamlining session management.",
       },
       {
         name: "SMF",

**Comment by Prid13** [comment]
https://github.com/working-group-two/wgtwo.com/pull/353
