### ISSUE TITLE
New case studies to be added

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#366]
Hi @Prid13 - here are two new case studies for you to add to two new links:

/showcase/mki
/showcase/mobi

See details for each in the project document (which you have access to on the link): https://docs.google.com/document/d/17Xrd-1JsShzXwefjm5HO5VWEIvmgmOhRm_cuCaJuHuE/edit

We'll ask you to add "Showcase" to our top menu bar at some point in the future. (Next to "Product Ecosystem"). But NOT for now.

**Comment by Prid13** [comment]
https://github.com/working-group-two/wgtwo.com/pull/368

**Comment by torotimes** [comment]
Looks good on the devserver. Thanks for that. 

I do think we need to do something with the design, though. There's now a big open gray field to the left. 

Let's put this one on the Mobi draft, at least:
![mobi](https://github.com/working-group-two/wgtwo.com/assets/98818609/428951ef-4b15-4a4e-82b6-45c30f4137c1)

Can you start with that, @Prid13 ?

**Comment by torotimes** [comment]
We could also use this one:

![image](https://github.com/working-group-two/wgtwo.com/assets/98818609/bd6164e9-e104-4ea3-ab4f-74de18f07e1c)

**Comment by Prid13** [comment]
Alright, I changed the size of the logos, so here's two options, since both look good imo 😅:

![Screenshot_8930](https://github.com/working-group-two/wgtwo.com/assets/27897747/b6b534c6-e68c-467e-a553-c8c5220bb460)

![Screenshot_8929](https://github.com/working-group-two/wgtwo.com/assets/27897747/e2411c26-8a9f-4be5-8345-a7ba03e93ef1)

**Comment by torotimes** [comment]
Let's do the one with nature!

**Comment by Prid13** [comment]
Just approve the PR :) It's failing bc 1 link is inactive.
