### ISSUE TITLE
Add "Showcase" menu button top menu and publish four showcases

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#375]
Hey @Prid13! 

This is one you've worked on previously, so it might just be about executing old code. 

Task:

**1. Make a PR to add the "Showcase" top menu button next to the "Product Ecosystem" button**
- It should have a dropdown functionality. 
- It does not need its own landing page like "Blog" has today - with an overview of all the showcases. Just a dropdown that points to three separate showcases:
Title: Mobi (MVNO/MNO). Link: https://www.wgtwo.com/showcase/mobi/
Title: CKH IOD (MVNE). Link: https://www.wgtwo.com/showcase/ckh-iod/
Title: Telenor Connexion (IoT). Link: (see below)
Title: MKI (Private Networks). Link: https://www.wgtwo.com/showcase/mki/

**2. Create a new case study (showcase/telenorconnexion/)**
(Put the beach image where you put Mobi's jungle image, please)

Challenge:
Telenor manages international IoT deployments for global customers in some 200 countries and today operates more than 20 million connected devices to enterprises such as Volvo, Scania, Hitachi, Verisure Securitas Direct and Husqvarna.

The gradual shutdown of legacy 2G/3G networks across the world makes VoLTE (Voice over LTE/4G) mandatory to provide voice services for critical use cases such as assistance calls for smart elevators, elderly monitoring, and car emergency/helpline calls.

Solution:
WG2 was selected to provide the VoLTE technology to Telenor Connexion’s subscribers, wherever in the world they have 4G network coverage only, delivered as-a-service. WG2’s VoLTE-as-a-service has been integrated with Telenor Connexion’s internal systems, as well as to relevant service partners platforms including the Aeris IoTA (Internet of Things Accelerator), to jointly operate for subscriber network access, authentication, and services profile. It has also been integrated to handle calls outside VoLTE domain (legacy mobile circuit switching / public switched telephone network). VoLTE from WG2 is built on IMS (IP Multimedia Subsystem) infrastructure, which enables voice and messaging over IP.

VoLTE-as-a-service provides benefits such as reduced infrastructure investment, rapid deployment, scalability, expertise and support, continuous upgrades and innovation, geographic reach, interconnectivity, and cost optimization.

Quote:
“For us, the scalability of VoLTE is of high essence. With a cloud-based solution delivered to us as a service we find that WG2 can fulfil our global scalability needs, while also complying to our high expectations of security and availability,” says Martin Whitlock, CTO, Telenor Connexion.

Quick fact:
20 million connected devices in the Telenor IoT network

Resources:
https://iot.telenor.com - Visit Telenor
Press release: https://www.wgtwo.com/blog/wg2-volte-for-iot/

![image](https://github.com/working-group-two/wgtwo.com/assets/98818609/25032e3d-aeda-4611-ba20-4e4040c24d00)

**3. Edit the text in the MKI case study (https://www.wgtwo.com/showcase/mki/)**
Challenge
Deploying new private networks is time-consuming and requires strong technical knowledge.

Traditionally private networks require on-premise deployments. These integrations of the radio spectrum and the maintenance of the infrastructure require detailed experience. Lastly, once deployed these integrations weren't evolved with later features requested by customers and not being implemented. This ultimately made it difficult for any stakeholders to build new businesses on top of the private network domain.

Solution:
LTE/5G cloud-based private network deployable anywhere.
WG2 enabled MKI to simplify the financial and operational aspects of the mobile system allowing their unique offering. The cloud-based private network can be scaled with MKI’s customer portfolio. On top of it, our initiative to enable zero-touch private networks deployment allows MKI to support both cloud-based and on-premise UPF flexibly, but kept as simple.

**Comment by Prid13** [comment]
Will have this done by the weekend at the latest, but hopefully by tomorrow 😇 btw love the formatting as always 💯

**Comment by Prid13** [comment]
1. https://github.com/working-group-two/wgtwo.com/pull/377
2. https://github.com/working-group-two/wgtwo.com/pull/376
3. https://github.com/working-group-two/wgtwo.com/pull/378

⭐

**Comment by torotimes** [comment]
GREAT work on this, @Prid13 ! 

It's now live on the site :)
