### ISSUE TITLE
Add language toggle (EN-JP)

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#379]
Hi @Prid13 - can you experiment with how we can set up a language toggle? To go from wgtwo.com to wgtwo.com/jp and back. 

Our issue today is that it is hard to find the /jp pages. 

We are not looking to localize our site to a bunch of other languages any time soon, so while we should always keep the future in mind, we don't have to design for a future where we have 20 different languages to choose between. 

The most obvious (and most standard UX) approach is to have a small flag/language toggle in the top right corner. Another is a flag or dropdown toggle in the bottom right. But I think we should look at doing something top right.  

As for the actual design, there are multiple options:
- Flag toggle (US <--> JP)
- Text toggle (English <--> Japanese)

Here's a simple rundown of some options: https://usersnap.com/blog/design-language-switch/

Have fun with playing around with options! 

I've included @naoya-wg2 in this issue for him to comment on the options directly (he's our main man in Japan!).

**Comment by jonny-wg2** [comment]
I think keeping the design simple with 

`EN | 日本`

And the laguage that is active is bold

**Comment by torotimes** [comment]
I think that makes sense, @jonny-wg2 :)

**Comment by Prid13** [comment]
Schwoop: https://github.com/working-group-two/wgtwo.com/pull/380

**Comment by jonny-wg2** [comment]
Doing something like this might be a clever solution too - https://ipapi.medium.com/change-website-based-on-visitors-country-using-javascript-514ccb5aef4d

Unsure how if it's the best solution though because then a japanese up could never access the English page?

**Comment by Prid13** [comment]
> Doing something like this might be a clever solution too - https://ipapi.medium.com/change-website-based-on-visitors-country-using-javascript-514ccb5aef4d

Aah, clever idea ;) but like you said, I already see some issues with it:

- There would be no way to change language and you'd be restricted to your location
- If you have VPN on, there might be some "unexpected" confusion for the end user 😅 (unlikely case, though)
- Where would such a global code be placed in Docusaurus?
- It's dependent on an external API, and that's no good :< there's probably a built-in JS method or library to do the same thing (unreliably), but perhaps it's a bit overkill just for JP users?

If there's some data on this we could make better evaluations 😇 What do you think?

I reckon most JP users find this website through Google or social media links, in which case it's probably the JP site that pops up, right?

**Comment by jonny-wg2** [comment]
Yeah you are totally right - bad idea!!

I just saw this website from a cold email and thought they have a good implementation (for reference) 

https://dataddo.com/

<img width="1023" alt="image" src="https://github.com/working-group-two/wgtwo.com/assets/39831372/e16af62b-7af1-4f5e-9238-68a4ef2373ad">
<img width="293" alt="image" src="https://github.com/working-group-two/wgtwo.com/assets/39831372/b06d1d92-4b12-4d50-8c80-bbfe7d5b6a64">

**Comment by Prid13** [comment]
Thanks for the feedback @jonny-wg2. Check this out: https://github.com/working-group-two/wgtwo.com/pull/386

**Comment by jonny-wg2** [comment]
Can we update the current implementation to match cloudflares? @Prid13 

![image](https://github.com/working-group-two/wgtwo.com/assets/39831372/3c0728e7-9f89-43ea-b912-ab21a25fd583)

![image](https://github.com/working-group-two/wgtwo.com/assets/39831372/3c31121c-c39e-4d73-b070-a8ff4fae9a53)

**Comment by torotimes** [comment]
This is a good solution, @jonny-wg2. 

@Prid13, can we implement that, and fix the issue on Windows? 

Jonny, @Prid13 also submitted this one, by the way, based on your input (I tried to approve it until we have something else in place but there was a prettier issue) https://github.com/working-group-two/wgtwo.com/pull/386

**Comment by jonny-wg2** [comment]
Ah just now saw #386  - looks much better! 👍🏻

**Comment by Prid13** [comment]
@jonny-wg2 that cloudflare example is good, but the only way I was able to make it work in Docusaurus without hacking the navbar was to hide the default element and replace with this another element on top with a Globe icon:

![image](https://github.com/working-group-two/wgtwo.com/assets/27897747/0ee31949-23d3-478b-9e2b-4e44451e1250)

Would have to add another element on top for the arrow 😅 You still want this, or? :)

**Comment by jonny-wg2** [comment]
Nice! I really like the above solution with the globe!

I vote we go with the globe if possible

A couple things to do
- [ ] Globe icon with drop down arrow
- [ ] Change label GB to `English`
- [ ] Change label JP to `日本`
- [ ] Make the drop down like cloudflare where the text is beneath one another
<img width="255" alt="image" src="https://github.com/working-group-two/wgtwo.com/assets/39831372/b318f5f7-b862-4386-8381-821d872587ac">

**Comment by Prid13** [comment]
Alright, finally got around to making a working solution :) It's a bit hacky, and I kinda hate that, but it works (on my laptop at least haha):

![image](https://github.com/working-group-two/wgtwo.com/assets/27897747/bf77f9ab-5efc-43d4-8fce-8d39f2be4729)
![image](https://github.com/working-group-two/wgtwo.com/assets/27897747/8a2bd37d-35fa-4b73-bc60-3d02d6b73dbc)

https://github.com/working-group-two/wgtwo.com/assets/27897747/7cbaf4c4-0e94-4914-a0e8-7bd97ff12b55

The globe and arrow icons are raw SVGs pulled from the Lucide library.

Also, the globe icon wasn't aligning percetly with the search icon in the navbar, so I tweaked it a bit by a few pixels. This may have varying results on different devices, so gotta test 😅

PR: https://github.com/working-group-two/wgtwo.com/pull/392

**Comment by jonny-wg2** [comment]
Merged! Looks amazing. Great work - was a journey to come up with a clever solution.

**Comment by Prid13** [comment]
> Merged! Looks amazing. Great work - was a journey to come up with a clever solution.

Yeah, thanks for all your input, research and inspiration with the examples, I love your willingness to aim for the top 😇👍
