### ISSUE TITLE
Add Marietta to section - Got a question? Talk to our friendly folks - on career site 

### ISSUE THREAD

**Issue by marietta-wg2** [working-group-two/wgtwo.com#390]
https://www.wgtwo.com/careers/ 
Add the third person to the section - Marietta, Recruiter, with the picture, in the same style as Victoria and Theresa
![marietta](https://github.com/working-group-two/wgtwo.com/assets/77273745/cae7c255-f6f2-4a0a-babf-d3199b5274de)

**Comment by Prid13** [comment]
![image](https://github.com/working-group-two/wgtwo.com/assets/27897747/ebefe1af-d2ee-4eb3-8dd8-099545b6ef36)

@marietta-wg2 Here you go 😇⭐ is the first name only okay? And is the email address correct? Let me know.

Here's the Pull Request where you can approve the changes to be merged into the main website: https://github.com/working-group-two/wgtwo.com/pull/391

**Comment by Prid13** [comment]
Good to go 😇👍

Just hit Approve or something at the bottom of this page: https://github.com/working-group-two/wgtwo.com/pull/391

Paging @torotimes and @jonny-wg2 to also approve the PR :)

**Comment by jonny-wg2** [comment]
Merged! Looks great!

**Comment by jonny-wg2** [comment]
@Prid13 as a follow up, could you center the text under the images. Would look better.

**Comment by Prid13** [comment]
> @Prid13 as a follow up, could you center the text under the images. Would look better.

https://github.com/working-group-two/wgtwo.com/pull/396

You've really got an eye for design! 👏 At this point you're the architect and I'm the builder 😅

**Comment by jonny-wg2** [comment]
💫
