### ISSUE TITLE
Update footer to include `HIRING` next to Careers

### ISSUE THREAD

**Issue by jonny-wg2** [working-group-two/wgtwo.com#393]
Many company websites will have a `HIRING` next to the careers on the footer. The aim of the game to update our footer and add a `HIRING` in all caps, next to Careers. As for the colors, perhaps we can keep the same theme with the light blue pill.

<img width="1293" alt="image" src="https://github.com/working-group-two/wgtwo.com/assets/39831372/07b39ee6-1a48-4d06-91f0-8518e2a846af">

<img width="196" alt="image" src="https://github.com/working-group-two/wgtwo.com/assets/39831372/177749d5-f24b-43d5-ae6b-7aac2b7569a1">

The pill we could use 
<img width="244" alt="image" src="https://github.com/working-group-two/wgtwo.com/assets/39831372/b5be3ef1-8324-424a-bf96-953254050996">

**Comment by Prid13** [comment]
Tried my hand at this:

![image](https://github.com/working-group-two/wgtwo.com/assets/27897747/f060b950-6300-478e-b852-f67d643f299c)

Had to specifically target the Careers footer item for this to work without hacking the footer code, but as long as the position is static, it should work long-term :)
