### ISSUE TITLE
[feature][blog] create a progress bar for when scrolling

### ISSUE THREAD

**Issue by jonny-wg2** [working-group-two/wgtwo.com#394]
As shown here https://zapier.com/blog/use-openai-gpt-3-for-content/ I noticed that there is a progress bar. Sort of cool.

In a quick google search I found https://codyhouse.co/ds/components/info/reading-progressbar - which looks like a good option.

So leveraging this for wgtwo.com/blog/articlexyz, and changing the color to match our accent blue that is used for the pills could be a nice feature and engagement for the blogs.

**Comment by Prid13** [comment]
Took a shot at this with a simple npm package I found: https://github.com/working-group-two/wgtwo.com/pull/402

The component you found unfortunately costs money x)
![image](https://github.com/working-group-two/wgtwo.com/assets/27897747/c5e4d1d1-005e-49c8-8efa-2df014beb3f8)

**Comment by jonny-wg2** [comment]
Implemented and works great!
