### ISSUE TITLE
Add new blog post

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#403]
Hi @Prid13 

Can you turn this one into a blog post on our site, please? 

https://aws.amazon.com/partners/success/three-solutions-group-csg-working-group-two/

Author should be "WG2"

Takk takk!

**Comment by Prid13** [comment]
Here you go: https://github.com/working-group-two/wgtwo.com/pull/405

Sorry for the delay, hopefully it can still be posted :)
