### ISSUE TITLE
Add company info to /jp

### ISSUE THREAD

**Issue by torotimes** [working-group-two/wgtwo.com#85]
Hi Steinar,

Let's add this as a new component on /jp

**Comment by torotimes** [comment]
![image](https://user-images.githubusercontent.com/98818609/175303971-67672f53-1d49-46a4-8f93-0fc7df9aac33.png)

**Comment by s-utstrand** [comment]
@torotimes Is the text in the grey area the heading? Should it be included in this component?

**Comment by torotimes** [comment]
> @torotimes Is the text in the grey area the heading? Should it be included in this component?

We'll get back to you asap about this. It probably means Company info or something. But confirming that.

**Comment by s-utstrand** [comment]
I think I found the answer myself :lau
![image](https://user-images.githubusercontent.com/104059760/175494008-77d921a9-6a14-4cd5-a2f1-28297f54362e.png)

**Comment by torotimes** [comment]
Indeed. Please use that. 🤓
